PR No 2
Robocraft999/TraidingNetwork pull request #4
Opened 2024-06-22 15:22 UTC by Darudas

I am a fan of the AmazingTrading mod and have been working on some enhancements to help it shine even more in the future. Here are the key improvements I've made:

### Enhancements

- **Missing Recipes**: Added the missing recipes to ensure all items can be processed correctly.
- **Shredder Enhancements**:
  - **Hopper-like Functionality**: The shredder can now automatically suck items into its inventory, making it more efficient and user-friendly.
  - **Item Display**: Items being processed by the shredder are now visually displayed, providing better feedback to the player.
  - **Universal Crushing**: The shredder can now crush any item, even those without predefined values. Crushed items are stored and can be bought back for 1 unit. Additionally, there is a 50/50 chance to gain 1 unit by shredding these items down.

### New Command

- **/amt increment <amount> Command**: Added a new command to increment the amount of a specific item in the player's shop inventory. 

I believe these enhancements and fixes will significantly improve the user experience and functionality of the mod. I look forward to your feedback and hope these changes can be integrated into the main project.

2024-06-23 02:45 UTC, Darudas commented
@Robocraft999

2024-06-23 10:21 UTC, Robocraft999 commented
So first of all I'm sorry that I let you wait and thanks for your work. But there are a few things I would change. The first thing is to maybe move the sucking of items to a seperate Block like a hopping shredder (extending the current). Furthermore there are some weird ways you try to get the resourcepoint values. The recipes are very nice though. The shredding of items without value I'm not sure about. I thought about maybe putting it beheind a config or something but it kind of breaks with the concept of only being to crush predefined items and not really being a trashcan. The command thing i would move to a seperate pr. I also will have to have a look at the displaying before merging. Also I have to get the fluid integration working I'm working on right now to release it alltogether as 0.2, but it's a bit broken right now.

2024-06-23 10:52 UTC, Robocraft999 commented
So i had a look now. The Item displaying looks very nice, the recipes are nice, but I don't understand why to add this command. Also the sucking seems only to work if the inventory is empty and single items sometimes don't get displayed.

2024-06-23 11:06 UTC, Robocraft999 requested changes

2024-06-23 11:06 UTC, Robocraft999 commented on src/main/java/com/robocraft999/amazingtrading/client/gui/shredder/ShredderInventory.java
> -/**
why remove this? Becuase its specified somewhere else?

2024-06-23 11:06 UTC, Robocraft999 commented on src/main/java/com/robocraft999/amazingtrading/content/shredder/CreateShredderBlockEntity.java
as said i maybe move the sucking to a hopping shredder (you dont have to), but please remove the shredding of all items

2024-06-23 11:06 UTC, Robocraft999 commented on src/main/java/com/robocraft999/amazingtrading/registry/ATBlocks.java
> -            .addLayer(() -> RenderType::cutoutMipped)
Im not even sure why it was there, but if ayou can please explain it to me

2024-06-23 19:20 UTC, Darudas reviewed
merge and remove or edit whatever you want and I will than work furter with your edits and sorry for all the leftovers as I am kinda new to git and still do most stuff the oldscool way with my limited knowladge and thats how some stuff gets removed or left from a side project with the code, I should start using branches xD

2024-06-23 19:20 UTC, Darudas commented on src/main/java/com/robocraft999/amazingtrading/client/gui/shredder/ShredderInventory.java
> -/**
that was not on purpose just happend while bug fixing and copy pasting stuff I guess

2024-06-23 19:20 UTC, Darudas commented on src/main/java/com/robocraft999/amazingtrading/client/gui/shredder/slots/SlotConsume.java
just rework/delete or whatever you want I just try to help with my limited knowledge and to acomplish something while learning

2024-06-23 19:20 UTC, Darudas commented on src/main/java/com/robocraft999/amazingtrading/registry/ATBlocks.java
> -            .addLayer(() -> RenderType::cutoutMipped)
public static final BlockEntry<? extends ShopBlock> SHOP = REGISTRATE
This line is not present in the files we read. However, it is a generic declaration that would allow for any subclass of ShopBlock to be assigned to SHOP. This is useful if there are multiple types of ShopBlock that might be registered and I guess we can use that way for registering another shredder

public static final BlockEntry<ShopBlock> SHOP = REGISTRATE
This line is registers a specific type of block, ShopBlock, with the REGISTRATE system to be exact.

 and last but not least

  .addLayer(() -> RenderType::cutoutMipped) 
thats a leftover from one try to fix the shop texture that the shadow does not glitch like it does at the moment

2024-06-23 19:23 UTC, Darudas commented
and I would love to talk to you in discord a bit about the mod to get a better understanding of what you want and what you dont want in the mod in the future and I would love to share you some of my workflows and would love to know what you think about it

2024-06-23 19:33 UTC, Robocraft999 commented
> merge and remove or edit whatever you want and I will than work furter with your edits and sorry for all the leftovers as I am kinda new to git and still do most stuff the oldscool way with my limited knowladge and thats how some stuff gets removed or left from a side project with the code, I should start using branches xD

Don't worry that's the same for me. I'm still afraid of using branches for everything and so on, but I think eventually I'll get used to it. (Also first time using this review feature of github for this pr). Regarding the discord thing, sure. Just contact me.

2024-06-23 19:49 UTC, Darudas commented
Ive send you a friend requests but because of your privacy settings I can't send you a massage

2024-07-06 08:41 UTC, Robocraft999 approved these changes

2024-07-06 08:42 UTC, merged